### ISSUE TITLE
Regarding the Promotion of Racial Categorization in Pursuit of Diversity

### ISSUE THREAD

**Issue by fantasai** [w3c/PWETF#362] opened 2023-11-14 05:45 UTC
I'm opening this issue, with permission, to raise a concern about the proposed Code of Conduct update and articulate a discussion that so far has been mostly off the written record. I think the concerns raised are reasonable, and since there doesn't seem to be general consensus on how to resolve this issue (yet anyway), I'm filing here in PWE but escalating to the AB for formal resolution (since the AB officially owns the CoC).

_Note: The issue relates to the discussions in https://github.com/w3c/PWETF/issues/327 https://github.com/w3c/PWETF/pull/338 and https://github.com/w3c/PWETF/issues/342 but concerns only one specific edit in the text, and its implications._

<hr>

<h3>Relevant Text</h3>

In [&sect;3.1 Expected Behavior](https://w3c.github.io/PWETF/#expected-behavior):
> 6. Be inclusive and promote **diversity**. Seek diverse perspectives. Diversity of views and of people powers innovation, even if it is not always comfortable. Encourage all voices. Help new perspectives be heard and listen actively.

In this expectation to “promote diversity“, the word “diversity“ is linked to the following glossary definition. (Note, this is the only place in the document that invokes this definition.)

> **Diversity** is variation across a wide range of identities, lived experiences, abilities, and perspectives.
> This can include, but is not limited to: socio-economic status, sexual orientation, religion, race, racial identity, physical appearance, neurotype, nationality, mental health, language, indigeneity, immigration status, gender, gender identity and gender expression, ethnicity, disability (both visible and invisible), caste, body, or age.

Thus, &sect;3.1 of the revised Code of Conduct includes an explicit exhortation to *promote diversity of race*, among other things.

_Note that the current CEPC does not list “race“ in its definition of diversity, so this implication is new to the revised text._

<h3>Problem Summary</h3>

Promoting diversity of race rests on the premise that race is a valid categorization of people. In some regions and cultures, this is an acceptable premise; however in others it is considered harmful.

An issue was therefore raised that “race“ should not be added to this particular list.

_Note that this issue explicitly is not about the lists that illustrate [Unacceptable Behavior](https://w3c.github.io/PWETF/#unacceptablebehavior) or [Discrimination](https://w3c.github.io/PWETF/#dfn-discriminate); everyone seems to agree that “race“ should remain in lists that describe undesirable behavior._

<h3>Background Context</h3>

“Race“ as a categorization of people has historically been intended, and etymologically derives, as a biological categorization. This perceived categorization has been used (and continues to be used) to discriminate against those perceived as belonging to inferior races. This biological classification is now widely recognized as invalid. Some people are re-interpreting “race“ as a cultural/ethnological shorthand; however this re-interpretation of a problematic concept is not universal, and the word retains its original meaning in English and in translation for much of the world's population.

W3C is a global organization that aims to be welcoming to everyone, everywhere.

<hr>

<h3>Issue Resolution</h3>

There are several possible changes that, afaict, would resolve this issue:

1. Remove the word “race“ from the list; it is not needed in a non-exhaustive list.
2. Modify the word “race“ to make it clear that is not a valid categorization of people, but that e.g. whether someone is perceived as belonging to a race is a way that people can be categorized.
3. Remove the list entirely; diversity is sufficiently well-defined without the list of examples.

There are also two ways to close this issue without changes:

<ol start=4>
<li>Invalidate the argument presented.
<li>In a response that articulates a clear understanding of both the argument in the issue and its counter-argument, provide a clear and straightforward explanation of each path forward and its merits and detriments, and provide compelling rationale for a resolution of no change as the best way forward.
</ol>

**Comment by nigelmegitt** [comment] 2023-11-14 10:51
> 2\. Modify the word “race“ to make it clear that is not a valid categorization of people, but that e.g. whether someone is perceived as belonging to a race is a way that people can be categorized.

Adding to the information about prior discussions relating to this topic: in https://www.w3.org/2023/08/29-pwe-minutes.html a discussion about using the term "ascribed race" occurred, which was further discussed at https://github.com/w3c/PWETF/pull/345#discussion_r1309073055

**Comment by chaals** [comment] 2023-11-14 15:45
I [commented](https://github.com/w3c/PWETF/issues/342#issuecomment-1810171748) in #342. I think it would be reasonable to reopen that issue and put the content from here into the discussion. To summarise my comment there, I'm not happy with the outcome of the discussion and support in particular the phrasing "perceived race and racial identity" over what we have now.

**Comment by jenstrickland** [comment] 2023-11-14 16:03
I was an active participant in the PWE's discussion and invited to review this issue by Wendy & Tzviya.

Fantasai's outline of the issue highlighted something that I think emphasizes the reason for "race" to remain in the list of characteristics that diversity **can** include:

> Note that this issue explicitly is not about the lists that illustrate [Unacceptable Behavior](https://w3c.github.io/PWETF/#unacceptablebehavior) or [Discrimination](https://w3c.github.io/PWETF/#dfn-discriminate); e**veryone seems to agree that “race“ should remain in lists that describe undesirable behavior**.

If "race" is something that a person can experience unacceptable behavior for, then it is also something that we would highlight as a diversity characteristic. As a multi-racial individual myself, I cannot get away from race. It is a part of my life experience and that of many of my family members, friends, and communities. Many of us live in societies that emphasize liberalist attachments to individual freedom, radical individualism, as a preeminent value, while also espousing a commitment to the greater good and public interest. As the W3C, we are responsible for the global community, to learn from and welcome the [pluriverse](https://radicalecologicaldemocracy.org/pluriverse/), which includes a variety of all realities—including "race" which we may not welcome but live with as a reality by which we are seen, and many now proudly claim in order to overcome.   We may aspire for a day when it can be erased, but it is very real today.

**Comment by npdoty** [comment] 2023-11-14 16:10
The list of identities and lived experiences doesn't seem to endorse that they are all beneficial, globally-welcome categorizations of people. For example, many would agree that grouping people into hierarchical castes is not beneficial. Nonetheless, it is a common categorization and it can be useful to our goal of diversity to promote inclusion of people of different castes, because of the difference in their lived experiences and a history of discrimination.

Perhaps we could add a sentence after the definition to clarify that this non-exhaustive list of identities and lived experiences is not a general endorsement of categorizing people in all of these ways, but is useful in recognizing the ways that people have been categorized.

**Comment by frivoal** [comment] 2023-11-15 02:46
> If "race" is something that a person can experience unacceptable behavior for, then it is also something that we would highlight as a diversity characteristic.

I don't think that necessarily follows. To give a counter example: burning witches is a despicable practice that needs the strongest rejection; it does not follow that witchcraft is desirable to highlight at a diversity characteristic. In fact, categorizing people as witches is part of the problem, not of the solution, and although people were ostensibly condemned for witchcraft, the underlying bigotry had little to do with magic, and a whole lot more to do with sexism.

**Comment by wareid** [comment] 2023-11-15 14:40
I'm not entirely sure I follow the logic @frivoal, since, as you point out, charges of witchcraft were often levied against women. Witchcraft charges were also laid against men, often men who did not fit societal standards or religious expectations. Today we might not include "witchcraft" as a dimension of diversity, but we do include gender, sexuality, neurotype, religious affiliation, etc. 

Any characteristic someone can be harmed for, is also something that shapes their lived experience. It shapes how they view the world, their perspectives. It means they may look at a problem or question differently from the person next to them. We _want_ that, we want people who see things differently. Every person is a sum of parts, and those parts are different for everyone, but we shouldn't invalidate any of those parts because we find them uncomfortable.

**Comment by jenstrickland** [comment] 2023-11-15 15:08
We -want- **need** people who experience racism to participate in our conversations. 

As someone who does get singled out for my race, I wish we had more in this conversation. If there were it would be really clear. As far as representation I don't see much in W3C activities. As someone who is less obviously of different ethnicities that are categorized as race in society, I would welcome more in order to address conversations like this. It's a reality we live with. 

Back in the day, we would likely list witches among possible diverse characteristics.

**Comment by dontcallmedom** [comment] 2023-11-15 15:16
although I come from a perspective that we shouldn't give any credit to the existence of race as a biological categorization, I think having it among a list of "lived experiences" in this context does match the reality of many people (racialization).

**Comment by dbooth-boston** [comment] 2023-11-15 15:48
> Any characteristic someone can be harmed for, is also something that shapes their lived experience.

Right, but the so-called "witches" were harmed because they were _perceived_ as being witches -- not because they really _were_ witches.  Similarly, people experience racial discrimination because of their _perceived_ race -- not because "race" is a valid way to categorize people.

We certainly want to encourage people who experience racism to participate, but racism is based on _perception_ of race -- not reality of so-called "race".

**Comment by torgo** [comment] 2023-11-15 16:22
First of all, I want to be on record as supporting any initiatives that can bring more witches to the W3C.

In all seriousness: I do believe we should be highlighting race / racial identity as part of how we encourage greater diversity at W3C (and not only as part of how we discourage bad behaviours and discrimination). I would like to point out that race is seen as a "protected characteristic" in many places in the world - I'll call out UK in particular: https://www.gov.uk/discrimination-your-rights. It’s not enough to discourage unwanted behaviours such as discrimination but we should also be actively building an anti-racist organization and in order to do that we must put in place a structure that engenders racial diversity. Note that racism is not only about biological factors. The concept of systemic racism / institutional racism see racism as "a system of advantage based on race". In order to dismantle that system, it must be acknowledged.

**Comment by jenstrickland** [comment] 2023-11-15 16:53
We don't actually know if they were witches or if witchcraft is harmful. 

I know people who practice witchcraft and identify as witches. 

I have to identify as Black--which is a "race"--a term used to categorize people who are dark. Being part of this social categorization comes with experiences that are unique and will benefit the W3C community to learn from. I am Black, no matter how others perceive me. 

> Right, but the so-called "witches" were harmed because they were _perceived_ as being witches -- not because they really _were_ witches.

**Comment by dbooth-boston** [comment] 2023-11-21 13:53
Perhaps the crux is whether the word "race" is being used to classify oneself or others.  

It's okay to classify oneself as a witch, but not okay to classify someone else as a witch (without consent).  The same goes for race.

It feels like we should simultaneously:

 - avoid language that implicitly endorses "race" as a valid way to classify *other* people;

 - validate people's right to classify their own "race", i.e., claiming their own racial identity; and

 - acknowledge that people are often classified by their perceived race, whether it is self perceived or others' perception.

**Comment by npdoty** [comment] 2023-11-21 14:42
If I opened a PR along the lines of my previous suggestion, would that address @dbooth-boston and @fantasai's requests here?

> Perhaps we could add a sentence after the definition to clarify that this non-exhaustive list of identities and lived experiences is not a general endorsement of categorizing people in all of these ways, but is useful in recognizing the ways that people have been categorized.

**Comment by jenstrickland** [comment] 2023-11-21 14:49
If one tells a Black person not to self-identify as Black, the Black person will likely 🤨. Race is a very complex topic and we cannot possibly act as though it doesn't exist. It is a category on government forms, for example. I am Black--I don't know what ethnicity is at the root of it due to historical circumstances.

This issue was addressed by the AB last week and accepted as previously decided.

**Comment by jenstrickland** [comment] 2023-11-21 14:51
Would it be welcome to open this discussion to the broader public since there are few here that check a race box on government forms?

**Comment by TzviyaSiegman** [comment] 2023-11-21 15:29
I am closing this issue. Thank you for a good discussion. PWE came to rough consensus to leave this as "race, racial identity" (https://www.w3.org/2023/09/26-pwe-minutes.html) and AB agreed in meeting on Nov 16 (minutes to come).

**Closed by TzviyaSiegman** 2023-11-21 15:29 UTC

**Comment by fantasai** [comment] 2023-11-21 20:35
@TzviyaSiegman Linking to the minutes doesn't really satisfy

> In a response that articulates a clear understanding of both the argument in the issue and its counter-argument, provide a clear and straightforward explanation of each path forward and its merits and detriments, and provide compelling rationale for a resolution of no change as the best way forward. 

It's fine to casually close issues that have a straightforward and easily understood resolution, but for controversial or complex topics, I think it's important to write a meaningful formal response [as required by the process](https://www.w3.org/2023/Process-20231103/#formal-address). In the CSSWG, this is typically the role of the editor; in this case, I'm not sure who it should be, but someone should do it.

**Comment by jenstrickland** [comment] 2023-11-21 21:10
I'm unsubscribing from this issue for now. If my input is needed please tag me. It's been a very difficult topic and has been a strain on my well-being at times as I perceived my reality was erased. I know we all have our perspectives and no harm was intended. I am taking care of myself as this is also a challenging time of year. Thanks for your patience and understanding.

**Comment by dbooth-boston** [comment] 2023-11-21 22:38
I too was puzzled by the abrupt closing of this issue with very little explanation.  I assume that the rationale was that, since the AB formally owns the CoC document, the AB decision of Nov 16 (which I have not yet seen) preempts the work of the PWE group and thus renders this discussion moot.

Terminology around "race" feels to me like an issue that should be reconsidered in a future version, even if it is settled for now by the AB decision.

> I perceived my reality was erased

I'm very sorry to read that.  I'm sure that was not anyone's intent.  It's pretty difficult to figure out the right balance of language that both acknowledges people's identities and experiences, and avoids implicit endorsement of harmful non-consensual categorizations.

**Comment by jenstrickland** [comment] 2023-11-21 23:02
If the purpose is to 

> avoids implicit endorsement of harmful non-consensual categorizations

A note could be added that listing the dimension is not an endorsement. 

The fact is it is on government forms, policies, and is in cases what some of us are left with as a description since our roots were erased. 

Unsubscribing didn't work. 🤕

**Comment by fantasai** [comment] 2023-11-22 00:19
>  I assume that the rationale was that, since the AB formally owns the CoC document, the AB decision of Nov 16 (which I have not yet seen) preempts the work of the PWE group and thus renders this discussion moot.

I think all that does is move the responsibility for the response to the AB, because that's where the resolution came from.

> A note could be added that listing the dimension is not an endorsement.

This was, I think, part of the AB resolution. But didn't get captured in Tzviya's comment. Another reason why it's good to write up formal responses...

>  is in cases what some of us are left with as a description since our roots were erased.

I thought this point was why "racial identity" was added to this list? And "race" was being kept for the experience of being treated a particular way by society categorizing you as a particular race. That was my understanding of the intention anyway...

Another reason why writing up formal responses is good: making sure it's clear what's the intention of the resolution.

> Unsubscribing didn't work. 🤕

Sorry. :(

**Comment by TzviyaSiegman** [comment] 2023-11-22 15:00
I had planned to discuss this in the meeting on 11/21, but I had to cancel at the last minute because my child was sick. I did not intend for this issue to balloon even more. Thank you for the discussion. I do not think revisiting issues that were discussed extensively in meetings is helpful. I apologize for any harm that this issue caused to individuals. I will write something up next week. We can briefly discuss in PWE on Dec 5. For those who celebrate, Happy Thanksgiving. For those who do not, enjoy the US being very quiet for a few days.
