### ISSUE TITLE
Sensitivity to contagion

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/PWETF#127] opened 2020-03-18 15:49 UTC
We already have an expected behavior which includes:

"For some cultures, overtly friendly disposition towards another participant involving body contact (e.g.: hugging, touching on the arm or shoulder, or kissing) is uncommon and may be perceived as an invasion of personal space, or as unwelcome advances. "

Should we add a sentence which says something like:

"During periods of contagion participants should be extremely careful to avoid close contact with others."

**Comment by nigelmegitt** [comment] 2020-03-18 17:04
Is there ever a period where there is no risk of contagion?

**Comment by jeffjaffe** [comment] 2020-03-18 17:53
Sure @nigelmegitt .  We could modify it to say during periods of rapid, deadly contagion.

**Comment by wareid** [comment] 2020-03-18 18:08
I feel like this is covered by the consent part later in the document. If I'm sick with a cold or flu and someone wants to shake hands, I'll just refuse with sickness as an excuse. I think it's a common courtesy we've all used.

**Comment by vlevantovsky** [comment] 2020-03-18 22:45
IMO, it would be beneficial to keep this section focused on behaviors that address cultural norms [and differences between them], and not dilute the CEPC with something that otherwise could be considered a common sense recommendation.

**Comment by TzviyaSiegman** [comment] 2020-04-21 14:47
4/21 meeting: proposed "avoid exposing others to contagious disease" and "respect requests for physical distancing and other precautions due to health concerns such as immune deficiency, allergies, or chemical sensitivity "

**Comment by vlevantovsky** [comment] 2020-04-21 15:19
I have an allergy to some (many) perfumes. Some of them are among my wife's favorites, and it is an ongoing battle trying to stop her using them. Knowing her likes and dislikes, I regularly try to bribe her by bringing other perfumes (those that I can live with) as gifts, and she likes them ... but once in a while she would put something on that makes my head spin, and there is almost nothing I can do about it! This is all to say that I cannot possibly demand that every meeting participant should stop doing what they do, I need to find a way to live with it.
On a slightly more serious note, I just want to remind us all that we are a group of accomplished professionals writing a Code of Conduct for a much larger audience of even more accomplished professionals. The advice to never forget washing your hands frequently is a good one, but may not be appropriate for certain audiences or certain settings.

**Comment by TzviyaSiegman** [comment] 2020-04-22 17:47
Thanks for the feedback, @vlevantovsky. As we have seen with the COVID-19 crisis, things that we hope are common sense, such as following government guidelines about social distancing or gathering in large groups, are not always followed. Our goal is to put an anchor in the CEPC to make sure that this sort of thing is included in formal documentation. We are not getting into the details of how this will be interpreted. As with many other items in CEPC, we hope people will be respectful, and we are not identifying every potential violation.

**Comment by vlevantovsky** [comment] 2020-04-23 15:34
> As we have seen with the COVID-19 crisis, things that we hope are common sense, such as following government guidelines about social distancing or gathering in large groups, are not always followed. Our goal is to put an anchor in the CEPC to make sure that this sort of thing is included in formal documentation.

This is actually the point I am trying to make. Yes, there are different groups of people _among general population_ that may decide not to follow guidelines or are lacking common sense altogether ... but they are not our audience! The "PC" part of CEPC stands for "professional conduct", and we should operate under the assumption that W3C membership is a group of distinguished professionals that don't need to be _told_ what to do, especially if things you want told _are_ common sense. In my opinion, it is disrespectful to even assume that W3C participants lack common sense, and this goes against everything we are trying to achieve with the CEPC.

**Comment by wareid** [comment] 2020-04-23 16:15
We talked about this a bit in the meeting, but maybe a better way to look at this is: it's common sense to follow advice and do the right thing in situations like these, and in general, you're right, the W3C is a collective of smart, sensible people who generally do that. 

However! One of the scenarios we talked about is different countries and government requirements. The example that came to mind was TPAC. The Canadian/British Columbian government may allow us to have TPAC, but likely with some guidelines in terms of safety/social distancing/PPE use/etc. Those guidelines will be communicated by the W3C as part of the materials for TPAC, and they might be stronger/weaker than the guidelines in countries participants come from, but we'd still expect them to be followed. If someone were to take issue with that, (who knows why but hey, people are varied and interesting), we can point the CEPC to say that it's within our professional conduct documents to provide these guidelines and expect them to be followed. 

There were some other examples mentioned in the meeting, not sure if they were all minuted, but I think these inclusions are fairly innocuous and respectful of both common sense and events/conditions that might require more guidance.

**Comment by jeffjaffe** [comment] 2020-04-23 17:16
Actually, @vlevantovsky there are many behaviors already in CEPC (but acceptable and unacceptable) that are also common sense.  But we have learned that there is a value in a formal code that states our values nonetheless.

**Comment by rachaelbradley** [comment] 2020-04-24 18:25
Hello. I am commenting regarding chemical sensitivity which I have been learning to live with the last few years. I've gone through recent minutes, this thread and other posts but likely missed things so please forgive me anything redundant or out-of-date. This is also slightly broader than the straight language but I hope will provide some insight and background. 

As a W3C participant, I've run into two environments where chemical sensitivity has been a barrier in participation. 

The first is in-person meetings which typically occur within an enclosed space with a number of people. This is the most difficult because if all participants haven't actively taken measures to provide a fragrance free environment, it is difficult to participate since its impossible to get away from any chemicals.  With COVID-19 that is even more difficult because of cleaning supplies and scented hand sanitizes.  The support needed for this environment is for organizers to request participants not use products with fragrances before coming to the meeting or while in the meeting. Ideally, this also involves contacting the venue to ensure bathrooms don't use scented soaps and hand sanitzers and that cleaning is done well before the room is used.  Practically, ensuring the pre-meeting accommodations requests include a way to allow participants to request this as an accommodation would a be very helpful practice. 

The second is hallway and other impromptu conversations. In this situation, members being aware that sometimes people add space or step away because they need to protect themselves and not get offended is the key point. 

From a language in the PWE point of view, I suggest the following addition for your consideration:

Within the expected behaviors section, I suggest text such as "Respect the accommodations needed for some participants. Some individuals may request you adjust how you interact such as slowing down speech and facing the participant. Some individuals may also need you to adjust personal care habits such as not wearing perfumes and other scented products. Please respect the need for these adjustments and work towards meeting them. "

A practical question, which I do not have a recommendation for, is how to handle in-person meetings where someone wears perfume/cologne and someone has chemical sensitivity. Both can't participate so who leaves and has a remote experience? Being prepared to support a virtual option is critical either way.

**Comment by brewerj** [comment] 2020-04-24 19:30
Rachael, thanks very much for giving us more background on this topic. One element of staying safe from Covid in the future may be certain aspects of advance precautions for attending a meeting (such as getting tested, or taking one's temperature in advance), and as you note precautions are an issue for chemical sensitivities as well. From your perspective, are there things that need to be asked of participants when registering for an event, and/or information included in event materials, that could reinforce W3C's being able to successfully accommodate people with allergies or chemical sensitivities in our events? 

Also, in response to your practical question, I've been in settings before where someone who's entered a meeting with strong perfume that is making it impossible for another person to stay in the room has willingly taken a brief washroom break to wash up and cut the intensity of whatever scented product was causing the problem. That may not be work in all cases, but in instances where it has been an issue, I would assume that that participants having clear notice of expectations in advance could factor into how this is handled.

**Comment by vlevantovsky** [comment] 2020-04-24 20:20
Hi Rachael,
Thank you for your post, and let me assure you that you have one very understanding soul here - I've been suffering from chemical sensitivity for over 20 years, ever since my wife discovered her newfound "love" for a certain perfume that makes her life happy and my life miserable (the first time I smelled it, it made me so dizzy that I could hardly stay upright). Later on, we both discovered that pretty much all perfumes she likes are made by [the name of one particular French perfume maker goes here], and they all trigger the same reaction. There is obviously a chemical component they use in their manufacturing process that I [quite literally] can't stand while upright, and it also makes me sneeze violently ... yes, we are still happily married!

The real challenge here is how we learn to deal with it. I happen to share the general belief that it is hard [to nearly impossible] to change the behavior of people around us, especially if there is nothing inherently wrong with their behavior. When it comes to my family, we both learned to work around things - e.g. my wife would put smaller amount of her favorite perfume on, right before she leaves home for work, and by the time she and I are back home together, the smell is faint enough to not trigger my sensitivity. Other times, I wasn't as lucky - one particular family car trip comes to mind when she absentmindedly put on the same perfume and we ended up in a position where we had to consider only two possible options: the trip is cancelled (one can't drive being dizzy) _or_ she goes back home and takes a shower (she did, but I'd never in a million years ask e.g. a coworker or a meeting participant to take a shower!)

So, I had to learn to deal with it on my own, even if, sometimes, it requires stepping away or moving to another part of the room from someone who wears a scent I am sensitive to. The real challenge here is that it is hard to demand people to change their habits (especially if they consider it a part of good hygiene and a good habit), it is even harder to try and make it a mandate (through CEPC or by any other means), and it is impossible to enforce the mandate - how can anyone be "punished" for their attempt to smell nice (again, we really can't force anyone to take a shower)! 

I think the most we can do is to add a very gentle reminder (somewhere in the "Expected behaviors" section that some participants may have a chemical sensitivity to certain scented products, and may need to distance themselves because of it. We _may_ even consider asking people to be respectful of these personal limitations and not wear strong perfumes while attending meetings, but I think this is as much as we can hope for. 

Personally, I find the proposed language to "respect requests for physical distancing and other precautions due to health concerns such as immune deficiency, allergies, or chemical sensitivity" a bit offensive - it's perfectly fine for me to take two steps back and apologize for my distancing due to sensitivity to someone wearing a perfume I am allergic to, but it is not OK for me to request that the person wearing a perfume should stay away from me because I am allergic to it.

**Comment by brewerj** [comment] 2020-04-24 21:10
Vladimir, W3C's Positive Work Environment Community Group focuses on issues relating to fostering inclusion in a work environment, so that all have an opportunity to contribute to building the Web. In some cases the approach we need to take in a workplace setting will differ from how individuals choose to handle such issues in their personal and home life.

**Comment by rachaelbradley** [comment] 2020-04-24 21:23
I agree it is very difficult to ask someone to change their personal hygiene habits and I intended no offense with the suggested wording. The opposite actually. I have been in numerous situations where I was unable to back away or when I did, an individual followed me forcing me to ask them to step away. I find that conversation much less awkward and offensive if someone is already aware of chemical sensitivity and the need to respect distance around it. In my experience pre-education makes support for this disability much easier, conversations less awkward, and behaviors less offensive. 

I realize that this is a disability that does not have the same awareness and history around it that others do.   As a result, asking for accommodations for it seem very difficult, and potentially offensive.   I frankly struggle with it every day.  The most proactive public support I've seen for accommodating chemical sensitivity is the [US Access Board's fragrance free policy](https://www.access-board.gov/the-board/policies/fragrance-free-environment). I am not pointing that out to say that W3C needs to adopt such an approach but rather to provide at least one example of a way that an organization has tried to handle the challenge this presents.

To Judy's points, I think that clear notice in advance makes the situation easier for all participants.  In advance of meetings, it is helpful to me as someone who has to request an accommodation to have an "other" field on the accommodations needed form since the request is non-standard.   In large conference room settings, the accommodation can be as simple as placing a few chairs in the back of the room with a note that says fragrance free seats but in a small room where we typically have working group meetings, the only solution that will allow me to participate in person is requesting participants plan ahead and providing a backup virtual option in case someone forgets.  Asking people to wash up can help but a great deal depends on what the fragrance is, whether the washroom has scented soap, how close the quarters are, and how sensitive the person with chemical sensitivity is. I think a virtual back up is likely a solution with a higher success rate and less offensive to the other participants.

**Comment by vlevantovsky** [comment] 2020-04-24 21:37
Thank you Rachael. Do you have any specific comments on the general approach I proposed in the last two paragraphs of my previous post? (I realize that my post was long, and that without TL; DR; section it required a bit of patience to reach the most important parts of it.)
I also think we need to differentiate between what we want to make a part of CEPC (i.e., what we expect from W3C participants) vs. what we expect from W3C organization, when it comes to providing accommodations for people with disabilities (which is likely to be mentioned in another document, other than CEPC).

**Comment by TzviyaSiegman** [comment] 2020-04-28 01:02
Thanks all for this fascinating discussion. We are trying to make the language in CEPC flexible enough to accommodate a variety of use cases, ranging from chemical sensitivities such as the perfume allergy that @vlevantovsky has described to camera flash causing seizures to airborne allergies that can be life-threatening to social distancing for someone who is immuno-compromised. I'm sure there are many scenarios of which I am unaware. Any phrasing we add serves as an anchor for future iterations of CEPC. We discussed whether we should get into issues around accessiblity at this stage and decided against it. We could write a treatise on accessibility in the CEPC. We are already past several rounds of review and adding this at a very late stage.

Here is my proposal, attempting to merge language agreed upon in the meeting and @rachaelbradley's proposal

Add to Unacceptable Behaviors:

> Avoid exposing others to contagious disease

Add to Expected Bahvaviors:

> Respect requests for physical distancing and other accommodations or precautions due to health concerns such as immune deficiency, allergies, or chemical sensitivity. 

I realize that this does not come close to the detail that @rachaelbradley included, but I think that by being intentionally vague we also leave the door open for other issues that we will hopefully add in a future version.

If you do not like this wording, please propose new wording and indicate whether you will formally object. I intend to close this issue and pass this along to PWE, W3M, and AB in the first week of May for final review.

**Comment by jeffjaffe** [comment] 2020-04-28 01:50
Thanks @TzviyaSiegman I mostly like the wording.

To be a bit pedantic, maybe the "unacceptable" behavior should be expressed as "Exposing others to contagious disease".  It is probably acceptable to "avoid exposing others" :)

**Comment by vlevantovsky** [comment] 2020-04-28 16:30
I like the pedantic approach to things (makes it better for us all as a result) so, for the "unacceptable" part of CEPC, I like the wording Jeff proposed.

As far as the "expected" behaviors are concerned, the reason I don't like the proposed wording "respect requests for physical distancing ..." is because this wording makes "I told him/her to stay away from me because I have perfume allergy, and he/she didn't" a valid complaint (rude, but valid nevertheless). It isn't, and shouldn't be, in my opinion. If one has a chemical sensitivity (like yours truly), it is his/her need to distance oneself from a source, and it can often be accomplished easily, without making requests. One may want to explain why he/she need to distance oneself, and I'd expect that need to be acknowledged and accommodated, but it doesn't (and shouldn't) rise to the level of making demands for other participants to comply with.

With this in mind, I suggest the updated wording to be added to "Expected Behaviors" section, as part of the bullet point that starts with "Think of others' needs from their point of view" (and added immediately after this sentence) to say "Accommodate their needs for physical distancing and other precautions due to health concerns such as immune deficiency, allergies, or chemical sensitivity."

**Comment by rachaelbradley** [comment] 2020-04-28 21:10
I like the revised suggested wording from @vlevantovsky.  I think it strikes an excellent balance between addressing the need and getting the tone right.

**Comment by TzviyaSiegman** [comment] 2020-04-29 17:35
Thanks @vlevantovsky. Since we are likely to add to this in future iterations (e.g. adding information about accessibility, allergies, other health issues), I would prefer to keep this as a separate bullet. I have no strong feelings about "accommodate" vs "respect", but it would not surprise me if others do.

**Comment by vlevantovsky** [comment] 2020-04-29 18:22
@TzviyaSiegman At the risk of being seen as pedantic (luckily, I am not the only one) - the main differentiation between the original proposed language and my suggested change is not about "accommodate" vs "respect", it is about making requests for physical distancing vs. acknowledging the needs for physical distancing. Accommodating those needs is what we expect other participants to do.

**Closed** 2020-05-06 01:07 UTC
