### ISSUE TITLE
Examples still has extraneous text

### ISSUE THREAD

**Issue by wseltzer** [w3c/PWETF#81] opened 2020-01-08 12:44 UTC
Did the group decide what to do with the examples of unacceptable behavior?

The text still reads "While we agree on the intent of this section, discussions about specific language, extent, specificity, and placement are still underway."

**Comment by wseltzer** [comment] 2020-01-08 12:46
I would also recommend that if included, the examples of unacceptable behavior be placed after the "Expected Behavior."

**Comment by TzviyaSiegman** [comment] 2020-01-08 17:53
This is fixed with #79

**Comment by TzviyaSiegman** [comment] 2020-01-08 18:06
> I would also recommend that if included, the examples of unacceptable behavior be placed after the "Expected Behavior."

@wseltzer are you suggesting reorganizing the document so that the Expected Behaviors section is first? 
PWE discussed this (I see minutes are a bit choppy, but they are at https://www.w3.org/2019/06/13-pwe-minutes.html.) We decided to place unacceptable behavior first because this is the more critical information often, and we felt it should be at the top.

**Comment by wseltzer** [comment] 2020-01-08 20:22
@TzviyaSiegman Yes, I'm suggesting that we reorder to put "Expected Behavior" before the long list of Unacceptables. Start positive, especially because the list of unacceptables is so long. 

I understand it can be useful to be extensive in the listing, to help set norms, but still think that shouldn't be the first thing people encounter in the document.

**Comment by AdaRoseCannon** [comment] 2020-01-08 20:39
I'm not 100% set against reordering it, but my concern is that people will get part way through the document get bored and leave and miss the main point of the document, which in my opinion is the 'don't do this' and 'what do you do if you mess up' part.

**Comment by TzviyaSiegman** [comment] 2020-01-09 15:19
Positive first is #86

**Closed by TzviyaSiegman** 2020-01-09 15:19 UTC
Labels: bug
